import { promises as fs } from "fs";
import path from "path";

export async function GET() {
  try {
    // Dados estáticos das IAs (simulando o XML)
    const aisData = [
      {
        id: "1",
        name: "ChatGPT",
        company: "OpenAI",
        description:
          "Assistente de IA conversacional avançado capaz de responder perguntas, escrever código, criar conteúdo e muito mais.",
        url: "https://chat.openai.com",
        popularity: "famous",
        pricing: "freemium",
        rating: 4.8,
        tags: ["Conversação", "Escrita", "Código", "Educação"],
        contentTypes: ["text"],
        developmentTools: ["coding"],
        restrictions: ["family-friendly"],
      },
      {
        id: "2",
        name: "DALL-E 3",
        company: "OpenAI",
        description:
          "Gerador de imagens de alta qualidade a partir de descrições em texto natural.",
        url: "https://openai.com/dall-e-3",
        popularity: "famous",
        pricing: "paid",
        rating: 4.6,
        tags: ["Geração de Imagens", "Arte", "Design"],
        contentTypes: ["image", "art"],
        developmentTools: [],
        restrictions: ["family-friendly"],
      },
      {
        id: "3",
        name: "Midjourney",
        company: "Midjourney Inc.",
        description:
          "Ferramenta de geração de arte digital e imagens usando inteligência artificial através do Discord.",
        url: "https://www.midjourney.com",
        popularity: "famous",
        pricing: "paid",
        rating: 4.7,
        tags: ["Arte Digital", "Criatividade", "Design"],
        contentTypes: ["image", "art"],
        developmentTools: [],
        restrictions: ["commercial"],
      },
      {
        id: "4",
        name: "GitHub Copilot",
        company: "GitHub/Microsoft",
        description:
          "Assistente de programação que sugere código e funções inteiras em tempo real.",
        url: "https://github.com/features/copilot",
        popularity: "famous",
        pricing: "paid",
        rating: 4.5,
        tags: ["Programação", "Desenvolvimento", "Automação"],
        contentTypes: ["text"],
        developmentTools: ["coding", "automation"],
        restrictions: ["commercial"],
      },
      {
        id: "5",
        name: "Stable Diffusion",
        company: "Stability AI",
        description:
          "Modelo de geração de imagens de código aberto que pode ser executado localmente.",
        url: "https://stablediffusionweb.com",
        popularity: "famous",
        pricing: "free",
        rating: 4.4,
        tags: ["Código Aberto", "Geração de Imagens", "Arte"],
        contentTypes: ["image", "art"],
        developmentTools: ["ai-dev"],
        restrictions: ["unrestricted"],
      },
      {
        id: "6",
        name: "Claude",
        company: "Anthropic",
        description:
          "IA conversacional focada em ser útil, inofensiva e honesta, excelente para análise e escrita.",
        url: "https://claude.ai",
        popularity: "famous",
        pricing: "freemium",
        rating: 4.6,
        tags: ["Conversação", "Análise", "Escrita", "Pesquisa"],
        contentTypes: ["text"],
        developmentTools: ["analytics"],
        restrictions: ["family-friendly"],
      },
      {
        id: "7",
        name: "Runway ML",
        company: "Runway",
        description:
          "Plataforma de criação de vídeos com IA, oferecendo edição e geração de conteúdo audiovisual.",
        url: "https://runwayml.com",
        popularity: "famous",
        pricing: "freemium",
        rating: 4.3,
        tags: ["Edição de Vídeo", "Geração de Vídeo", "Criatividade"],
        contentTypes: ["video"],
        developmentTools: [],
        restrictions: ["commercial"],
      },
      {
        id: "8",
        name: "Jasper AI",
        company: "Jasper",
        description:
          "Assistente de escrita especializado em marketing e criação de conteúdo comercial.",
        url: "https://www.jasper.ai",
        popularity: "famous",
        pricing: "paid",
        rating: 4.2,
        tags: ["Marketing", "Copywriting", "Conteúdo"],
        contentTypes: ["text"],
        developmentTools: [],
        restrictions: ["commercial"],
      },
      {
        id: "9",
        name: "DeepL Write",
        company: "DeepL",
        description:
          "Ferramenta de escrita e tradução que melhora textos em múltiplos idiomas.",
        url: "https://www.deepl.com/write",
        popularity: "anonymous",
        pricing: "freemium",
        rating: 4.1,
        tags: ["Tradução", "Escrita", "Idiomas"],
        contentTypes: ["text"],
        developmentTools: [],
        restrictions: ["family-friendly"],
      },
      {
        id: "10",
        name: "Eleven Labs",
        company: "Eleven Labs",
        description:
          "Plataforma de síntese de voz e clonagem vocal com qualidade realística.",
        url: "https://elevenlabs.io",
        popularity: "trending",
        pricing: "freemium",
        rating: 4.5,
        tags: ["Síntese de Voz", "Áudio", "Narração"],
        contentTypes: ["audio"],
        developmentTools: [],
        restrictions: ["commercial"],
      },
      {
        id: "11",
        name: "Character.AI",
        company: "Character.AI",
        description:
          "Plataforma para criar e conversar com personagens de IA personalizados.",
        url: "https://character.ai",
        popularity: "trending",
        pricing: "freemium",
        rating: 4.0,
        tags: ["Entretenimento", "Conversação", "Roleplay"],
        contentTypes: ["text"],
        developmentTools: [],
        restrictions: ["family-friendly"],
      },
      {
        id: "12",
        name: "Perplexity AI",
        company: "Perplexity",
        description:
          "Motor de busca conversacional que fornece respostas com fontes citadas.",
        url: "https://www.perplexity.ai",
        popularity: "trending",
        pricing: "freemium",
        rating: 4.3,
        tags: ["Pesquisa", "Busca", "Informação"],
        contentTypes: ["text"],
        developmentTools: ["analytics"],
        restrictions: ["family-friendly"],
      },
      {
        id: "13",
        name: "Tabnine",
        company: "Tabnine",
        description:
          "Assistente de código com IA que oferece sugestões inteligentes durante a programação.",
        url: "https://www.tabnine.com",
        popularity: "anonymous",
        pricing: "freemium",
        rating: 4.1,
        tags: ["Programação", "IDE", "Autocompletar"],
        contentTypes: ["text"],
        developmentTools: ["coding", "automation"],
        restrictions: ["commercial"],
      },
      {
        id: "14",
        name: "Replit Ghostwriter",
        company: "Replit",
        description:
          "IA integrada ao ambiente de desenvolvimento Replit para assistir na programação.",
        url: "https://replit.com",
        popularity: "anonymous",
        pricing: "paid",
        rating: 4.0,
        tags: ["Programação", "Desenvolvimento Web", "Colaboração"],
        contentTypes: ["text"],
        developmentTools: ["coding", "ai-dev"],
        restrictions: ["family-friendly"],
      },
      {
        id: "15",
        name: "Hugging Face Transformers",
        company: "Hugging Face",
        description:
          "Biblioteca open source com milhares de modelos de IA pré-treinados.",
        url: "https://huggingface.co",
        popularity: "famous",
        pricing: "free",
        rating: 4.6,
        tags: ["Open Source", "Machine Learning", "Modelos"],
        contentTypes: ["text", "image", "audio"],
        developmentTools: ["ai-dev", "analytics"],
        restrictions: ["unrestricted"],
      },
      {
        id: "16",
        name: "Google Bard",
        company: "Google",
        description:
          "Chatbot conversacional do Google baseado no modelo LaMDA.",
        url: "https://bard.google.com",
        popularity: "famous",
        pricing: "free",
        rating: 4.2,
        tags: ["Conversação", "Pesquisa", "Google"],
        contentTypes: ["text"],
        developmentTools: ["analytics"],
        restrictions: ["family-friendly"],
      },
      {
        id: "17",
        name: "SoulGen",
        company: "SoulGen",
        description:
          "Gerador de arte com foco em personagens anime e conteúdo adulto.",
        url: "https://www.soulgen.ai",
        popularity: "anonymous",
        pricing: "freemium",
        rating: 3.8,
        tags: ["Anime", "Arte", "Personagens"],
        contentTypes: ["image", "art"],
        developmentTools: [],
        restrictions: ["adult"],
      },
      {
        id: "18",
        name: "AIVA",
        company: "AIVA Technologies",
        description:
          "Compositor de música artificial que cria trilhas sonoras originais.",
        url: "https://www.aiva.ai",
        popularity: "anonymous",
        pricing: "freemium",
        rating: 4.0,
        tags: ["Música", "Composição", "Trilha Sonora"],
        contentTypes: ["audio"],
        developmentTools: [],
        restrictions: ["commercial"],
      },
      {
        id: "19",
        name: "Mubert",
        company: "Mubert",
        description:
          "Gerador de música ambiente e trilhas para streaming, vídeos e aplicativos.",
        url: "https://mubert.com",
        popularity: "anonymous",
        pricing: "freemium",
        rating: 3.9,
        tags: ["Música Ambiente", "Streaming", "Background"],
        contentTypes: ["audio"],
        developmentTools: [],
        restrictions: ["commercial"],
      },
      {
        id: "20",
        name: "Zapier",
        company: "Zapier",
        description:
          "Plataforma de automação que conecta diferentes aplicativos usando IA.",
        url: "https://zapier.com",
        popularity: "famous",
        pricing: "freemium",
        rating: 4.4,
        tags: ["Automação", "Integração", "Workflow"],
        contentTypes: ["text"],
        developmentTools: ["automation", "analytics"],
        restrictions: ["commercial"],
      },
      {
        id: "21",
        name: "Copy.ai",
        company: "Copy.ai",
        description:
          "Ferramenta de copywriting com IA para marketing e criação de conteúdo.",
        url: "https://www.copy.ai",
        popularity: "trending",
        pricing: "freemium",
        rating: 4.1,
        tags: ["Copywriting", "Marketing", "Conteúdo"],
        contentTypes: ["text"],
        developmentTools: [],
        restrictions: ["commercial"],
      },
      {
        id: "22",
        name: "Luma AI",
        company: "Luma",
        description:
          "Criação de modelos 3D e vídeos a partir de imagens usando IA.",
        url: "https://lumalabs.ai",
        popularity: "trending",
        pricing: "free",
        rating: 4.2,
        tags: ["3D", "Modelagem", "Vídeo"],
        contentTypes: ["video", "image"],
        developmentTools: [],
        restrictions: ["family-friendly"],
      },
      {
        id: "23",
        name: "Synthesia",
        company: "Synthesia",
        description:
          "Plataforma de criação de vídeos com avatares de IA que falam.",
        url: "https://www.synthesia.io",
        popularity: "famous",
        pricing: "paid",
        rating: 4.0,
        tags: ["Vídeo", "Avatares", "Apresentação"],
        contentTypes: ["video"],
        developmentTools: [],
        restrictions: ["commercial"],
      },
      {
        id: "24",
        name: "Grammarly",
        company: "Grammarly",
        description:
          "Assistente de escrita com IA para correção gramatical e melhoria de textos.",
        url: "https://www.grammarly.com",
        popularity: "famous",
        pricing: "freemium",
        rating: 4.5,
        tags: ["Gramática", "Escrita", "Correção"],
        contentTypes: ["text"],
        developmentTools: [],
        restrictions: ["family-friendly"],
      },
      {
        id: "25",
        name: "Notion AI",
        company: "Notion Labs",
        description:
          "IA integrada ao Notion para auxiliar na escrita e organização de conteúdo.",
        url: "https://www.notion.so/product/ai",
        popularity: "famous",
        pricing: "paid",
        rating: 4.3,
        tags: ["Produtividade", "Escrita", "Organização"],
        contentTypes: ["text"],
        developmentTools: [],
        restrictions: ["commercial"],
      },
    ];

    return Response.json(aisData);
  } catch (error) {
    console.error("Erro ao buscar dados das IAs:", error);
    return Response.json(
      { error: "Erro interno do servidor" },
      { status: 500 },
    );
  }
}
